version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run: mkdir artifacts

      - run:
          name: Build
          command: |
            ./gradlew assembleDebug
            ./gradlew testDebugUnitTest

      - store_artifacts:
          path: ~/artifacts
          destination: env